#! /bin/sh
# Does NAT so machines on the bridge can access the IPV4 network

set -e

# Only for bridge interface

echo "nat-for-bridge[$MODE][$IFACE][$ADDRFAM]" >> /var/log/platformlayer

if [ "$MODE" != start ]; then
	echo "MODE != start; exiting"
	exit 0
fi

if [ "$IFACE" != ${bridgeInterface} ]; then
	echo "IFACE != --all; exiting"
	exit 0
fi

if [ "$ADDRFAM" != "inet" ]; then
	echo "ADDRFAM != --meta; exiting"
	exit 0
fi


# We need to forward everything... (this takes place after inbound NAT rules?)
#iptables -A FORWARD -i ${publicInterface} -o ${bridgeInterface} -m state --state RELATED,ESTABLISHED -j ACCEPT

iptables -A FORWARD -i ${publicInterface} -o ${bridgeInterface} -j ACCEPT
iptables -A FORWARD -i ${bridgeInterface} -o ${publicInterface} -j ACCEPT
iptables -A FORWARD -i ${bridgeInterface} -o ${bridgeInterface} -j ACCEPT

iptables -t nat -A POSTROUTING -o ${publicInterface} -j MASQUERADE

ip6tables -A FORWARD -i ${publicInterface} -o ${bridgeInterface} -j ACCEPT
ip6tables -A FORWARD -i ${bridgeInterface} -o ${publicInterface} -j ACCEPT
ip6tables -A FORWARD -i ${bridgeInterface} -o ${bridgeInterface} -j ACCEPT

exit 0

