// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JobData.protobuf

package org.platformlayer.ops.jobstore.protobuf;

public final class JobDataProtobuf {
  private JobDataProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface JobLogLineOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 timestamp = 1;
    boolean hasTimestamp();
    long getTimestamp();
    
    // optional string message = 2;
    boolean hasMessage();
    String getMessage();
    
    // optional int32 level = 3;
    boolean hasLevel();
    int getLevel();
    
    // optional .JobLogExceptionInfo exception = 4;
    boolean hasException();
    org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo getException();
    org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfoOrBuilder getExceptionOrBuilder();
    
    // optional string type = 5;
    boolean hasType();
    String getType();
  }
  public static final class JobLogLine extends
      com.google.protobuf.GeneratedMessage
      implements JobLogLineOrBuilder {
    // Use JobLogLine.newBuilder() to construct.
    private JobLogLine(Builder builder) {
      super(builder);
    }
    private JobLogLine(boolean noInit) {}
    
    private static final JobLogLine defaultInstance;
    public static JobLogLine getDefaultInstance() {
      return defaultInstance;
    }
    
    public JobLogLine getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.internal_static_JobLogLine_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.internal_static_JobLogLine_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 timestamp = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // optional string message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.Object message_;
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          message_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 level = 3;
    public static final int LEVEL_FIELD_NUMBER = 3;
    private int level_;
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getLevel() {
      return level_;
    }
    
    // optional .JobLogExceptionInfo exception = 4;
    public static final int EXCEPTION_FIELD_NUMBER = 4;
    private org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo exception_;
    public boolean hasException() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo getException() {
      return exception_;
    }
    public org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfoOrBuilder getExceptionOrBuilder() {
      return exception_;
    }
    
    // optional string type = 5;
    public static final int TYPE_FIELD_NUMBER = 5;
    private java.lang.Object type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          type_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      timestamp_ = 0L;
      message_ = "";
      level_ = 0;
      exception_ = org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo.getDefaultInstance();
      type_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMessageBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, exception_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMessageBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, exception_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLineOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.internal_static_JobLogLine_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.internal_static_JobLogLine_fieldAccessorTable;
      }
      
      // Construct using org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getExceptionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (exceptionBuilder_ == null) {
          exception_ = org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo.getDefaultInstance();
        } else {
          exceptionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine.getDescriptor();
      }
      
      public org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine getDefaultInstanceForType() {
        return org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine.getDefaultInstance();
      }
      
      public org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine build() {
        org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine buildPartial() {
        org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine result = new org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (exceptionBuilder_ == null) {
          result.exception_ = exception_;
        } else {
          result.exception_ = exceptionBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine) {
          return mergeFrom((org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine other) {
        if (other == org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasException()) {
          mergeException(other.getException());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              message_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              level_ = input.readInt32();
              break;
            }
            case 34: {
              org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo.Builder subBuilder = org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo.newBuilder();
              if (hasException()) {
                subBuilder.mergeFrom(getException());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setException(subBuilder.buildPartial());
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              type_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 timestamp = 1;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string message = 2;
      private java.lang.Object message_ = "";
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      void setMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
      }
      
      // optional int32 level = 3;
      private int level_ ;
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getLevel() {
        return level_;
      }
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000004;
        level_ = value;
        onChanged();
        return this;
      }
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        level_ = 0;
        onChanged();
        return this;
      }
      
      // optional .JobLogExceptionInfo exception = 4;
      private org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo exception_ = org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo, org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo.Builder, org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfoOrBuilder> exceptionBuilder_;
      public boolean hasException() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo getException() {
        if (exceptionBuilder_ == null) {
          return exception_;
        } else {
          return exceptionBuilder_.getMessage();
        }
      }
      public Builder setException(org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo value) {
        if (exceptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          exception_ = value;
          onChanged();
        } else {
          exceptionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setException(
          org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo.Builder builderForValue) {
        if (exceptionBuilder_ == null) {
          exception_ = builderForValue.build();
          onChanged();
        } else {
          exceptionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeException(org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo value) {
        if (exceptionBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              exception_ != org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo.getDefaultInstance()) {
            exception_ =
              org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo.newBuilder(exception_).mergeFrom(value).buildPartial();
          } else {
            exception_ = value;
          }
          onChanged();
        } else {
          exceptionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearException() {
        if (exceptionBuilder_ == null) {
          exception_ = org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo.getDefaultInstance();
          onChanged();
        } else {
          exceptionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo.Builder getExceptionBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getExceptionFieldBuilder().getBuilder();
      }
      public org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfoOrBuilder getExceptionOrBuilder() {
        if (exceptionBuilder_ != null) {
          return exceptionBuilder_.getMessageOrBuilder();
        } else {
          return exception_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo, org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo.Builder, org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfoOrBuilder> 
          getExceptionFieldBuilder() {
        if (exceptionBuilder_ == null) {
          exceptionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo, org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo.Builder, org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfoOrBuilder>(
                  exception_,
                  getParentForChildren(),
                  isClean());
          exception_ = null;
        }
        return exceptionBuilder_;
      }
      
      // optional string type = 5;
      private java.lang.Object type_ = "";
      public boolean hasType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      void setType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        type_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:JobLogLine)
    }
    
    static {
      defaultInstance = new JobLogLine(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:JobLogLine)
  }
  
  public interface JobLogExceptionInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string info = 1;
    java.util.List<String> getInfoList();
    int getInfoCount();
    String getInfo(int index);
  }
  public static final class JobLogExceptionInfo extends
      com.google.protobuf.GeneratedMessage
      implements JobLogExceptionInfoOrBuilder {
    // Use JobLogExceptionInfo.newBuilder() to construct.
    private JobLogExceptionInfo(Builder builder) {
      super(builder);
    }
    private JobLogExceptionInfo(boolean noInit) {}
    
    private static final JobLogExceptionInfo defaultInstance;
    public static JobLogExceptionInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public JobLogExceptionInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.internal_static_JobLogExceptionInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.internal_static_JobLogExceptionInfo_fieldAccessorTable;
    }
    
    // repeated string info = 1;
    public static final int INFO_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList info_;
    public java.util.List<String>
        getInfoList() {
      return info_;
    }
    public int getInfoCount() {
      return info_.size();
    }
    public String getInfo(int index) {
      return info_.get(index);
    }
    
    private void initFields() {
      info_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < info_.size(); i++) {
        output.writeBytes(1, info_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < info_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(info_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getInfoList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.internal_static_JobLogExceptionInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.internal_static_JobLogExceptionInfo_fieldAccessorTable;
      }
      
      // Construct using org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        info_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo.getDescriptor();
      }
      
      public org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo getDefaultInstanceForType() {
        return org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo.getDefaultInstance();
      }
      
      public org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo build() {
        org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo buildPartial() {
        org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo result = new org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          info_ = new com.google.protobuf.UnmodifiableLazyStringList(
              info_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.info_ = info_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo) {
          return mergeFrom((org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo other) {
        if (other == org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo.getDefaultInstance()) return this;
        if (!other.info_.isEmpty()) {
          if (info_.isEmpty()) {
            info_ = other.info_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInfoIsMutable();
            info_.addAll(other.info_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureInfoIsMutable();
              info_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string info = 1;
      private com.google.protobuf.LazyStringList info_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          info_ = new com.google.protobuf.LazyStringArrayList(info_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getInfoList() {
        return java.util.Collections.unmodifiableList(info_);
      }
      public int getInfoCount() {
        return info_.size();
      }
      public String getInfo(int index) {
        return info_.get(index);
      }
      public Builder setInfo(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInfoIsMutable();
        info_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addInfo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInfoIsMutable();
        info_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllInfo(
          java.lang.Iterable<String> values) {
        ensureInfoIsMutable();
        super.addAll(values, info_);
        onChanged();
        return this;
      }
      public Builder clearInfo() {
        info_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addInfo(com.google.protobuf.ByteString value) {
        ensureInfoIsMutable();
        info_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:JobLogExceptionInfo)
    }
    
    static {
      defaultInstance = new JobLogExceptionInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:JobLogExceptionInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_JobLogLine_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_JobLogLine_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_JobLogExceptionInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_JobLogExceptionInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020JobData.protobuf\"v\n\nJobLogLine\022\021\n\ttime" +
      "stamp\030\001 \001(\003\022\017\n\007message\030\002 \001(\t\022\r\n\005level\030\003 " +
      "\001(\005\022\'\n\texception\030\004 \001(\0132\024.JobLogException" +
      "Info\022\014\n\004type\030\005 \001(\t\"#\n\023JobLogExceptionInf" +
      "o\022\014\n\004info\030\001 \003(\tB)\n\'org.platformlayer.ops" +
      ".jobstore.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_JobLogLine_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_JobLogLine_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_JobLogLine_descriptor,
              new java.lang.String[] { "Timestamp", "Message", "Level", "Exception", "Type", },
              org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine.class,
              org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogLine.Builder.class);
          internal_static_JobLogExceptionInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_JobLogExceptionInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_JobLogExceptionInfo_descriptor,
              new java.lang.String[] { "Info", },
              org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo.class,
              org.platformlayer.ops.jobstore.protobuf.JobDataProtobuf.JobLogExceptionInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
