#!/bin/bash -e

echo $$ > /var/run/dnsdatabasemonitor.pid

while [ 1 ]; do
	if [ -e /var/dns/dirty ]
	then
		# We need to remove the dirty flag before we start processing, so that if someone immediately re-dirties, we won't miss it
		rm /var/dns/dirty
		
		# Later versions support scanning a directory...
		#tinydns-data /var/dns/records/ || logger -s "Error rebuilding tinydns data"
		
		WORKDIR=`mktemp -d`
		pushd ${WORKDIR}
		find /var/dns/records/ -type f | xargs cat > ${WORKDIR}/data
		mv ${WORKDIR}/data /var/tinydns/root/data
		popd
		
		pushd /var/tinydns/root/
		tinydns-data || logger -s "Error rebuilding tinydns data"
		popd
		
		# TODO: Re-dirty on failure
	fi

	sleep 1
done