#!/bin/bash

# TODO: Should we run log??

case "$1" in
	start)	echo "Starting tinydns."
			pushd /var/tinydns/
			exec ./run &
			popd
			echo $! > /var/run/tinydns.pid
			;;
			
	stop)	echo "Shutting down tinydns."
			kill `cat /var/run/tinydns.pid`
			rm -f /var/run/tinydns.pid
			;;

	*)		echo "Usage: $0 {start|stop}"
			exit 1
esac

exit 0