#! /bin/sh
# Apply iptables rules when an interface comes up
# (We pre-up with it in 'lockdown', and then open the ports)
# (Based on the OpenSSH script)

set -e

echo "if-up.d/iptables-ifup[$IFACE][$ADDRFAM]" >> /var/log/platformlayer

# Only run from ifup.
if [ "$MODE" != start ]; then
	echo "Not run from ifup; exiting"
	exit 0
fi

# Run any scripts in the directory e.g. /etc/iptables/eth0/inet6
if [ -e /etc/iptables/${IFACE}/${ADDRFAM} ]; then
	run-parts --verbose /etc/iptables/${IFACE}/${ADDRFAM} >> /var/log/platformlayer 2>&1
fi

if [ "$IFACE" = "--all" ]; then
	if [ "$ADDRFAM" = "meta" ]; then
		echo "Found --all / meta; running everything" >> /var/log/platformlayer 
 		find /etc/iptables/ -type d | xargs -L 1 run-parts --verbose >> /var/log/platformlayer 2>&1
	fi
fi

exit 0
